var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var userSchema = new Schema({

  userId : {type:String,default:"",required:true},
  username : {type:String,default:"",required:true},
  email : {type:String,default:"",required:true},
  role : {type:String,default:"student"},
  fullName : {type:String,default:null},
  salt : {type:String,default:""},
  passwordHash : {type:String,default:""},
  password : {type:String,default:"",required:true},
  imageName:{type:String,default:""},
  fileSize:{type:String,default:""},
  type:{type:String,default:""} ,
  doc_id: {type:String,default:"",required:true},
  createdOn : {type:Date,default:Date.now},
  updatedOn : {type:Date,default:Date.now},
  status : {type:String,default:"active",required:true},
  calendarOnOff : {type:String,default:"false",required:true},
  bankDetails: { type: Object, default: null },
  departmentName : {type:String,default:"",required:true},
  courseName : {type:String,default:"",required:true},
  academicYear : {type:String,default:"",required:true},
  loginCount : {type:String,default:"0"} ,
  onboarding :{type:String,default:"yes"},
  theme : {type:String,default:"default"},
  courseId :{type:String,required:true},
  mobile :{type:String,default:""},
  panId :{type:String,default:""},
  studentId : {type:String,default:"",required:true},
  altemail : {type:String,default:""},
  altmobile :{type:String,default:""},
  dateOfBirth : {type:String,default:""},
  gender :{type:String,default:""},
  aadhar : {type:String,default:""},
  linkedinlink : {type:String,default:""},
  jobDescreption : {type:String,default:""},
  experience : {type:String,default:""},
  lastLoginDate: {type: String},
  lastLoginTime: {type: String},
});
mongoose.model('User',userSchema);
